## Álgebra Lineal Computacional - 2C 2022


### Arrays

Seguimos trabajando con matrices, veremos algunas funciones más, de Python y de Numpy en particular, para luego usar algunos comandos como **for** e **if**.


Importemos Numpy e ingresemos las matrices $$A = \begin{pmatrix} 0 & 1 & 2 \\ -3 & -4 & -5 \\ 6 & 7 & 8 \end{pmatrix} \quad B= \begin{pmatrix} 1 & 0 \\ 0 & -1 \\ 2 & 3 \end{pmatrix}$$
para aplicarles algunas funciones:

In [10]:
import numpy as np

#Definimos la matriz A
A = np.array([[0,1,2],
             [-3,-4,-5],
             [6,7,8]])

print('Matriz A: 3x3\n',A)

#Definimos la matriz B
B = np.array([[1,0],
             [0,-1],
             [2,3]])

print('Matriz B: 3x2\n',B)

Matriz A: 3x3
 [[ 0  1  2]
 [-3 -4 -5]
 [ 6  7  8]]
Matriz B: 3x2
 [[ 1  0]
 [ 0 -1]
 [ 2  3]]


### Transpuesta de una matriz

Si $A\in \mathbb{K}^{m\times n}$ la matriz transpuesta de $A$ es la matriz $A^t \in \mathbb{K}^{n\times m}$ que tiene por filas a las culumnas de $A$. 

$(A^t)_{ij}=a_{ji} \quad \forall 1\leq i\leq n, 1\leq j \leq m$.

La transpuesta de una matriz la calculamos agregando ".T" a la matriz. Calculemos $ A^t $ y $ (A.B)^t $. 

Recordar que multiplicamos matrices con "@".

In [23]:
#Definimos la matriz transpuesta de A
At= A.T
print('Matriz transpuesta de A:\n',At)

#Definimos el producto entre la matriz A y B, luego la transponemos
ABt= (A@B).T
print('Producto : (A.B)**t\n',ABt)


Matriz transpuesta de A:
 [[ 0 -3  6]
 [ 1 -4  7]
 [ 2 -5  8]]
Producto : (A.B)**t
 [[  4 -13  22]
 [  5 -11  17]]


Podemos observar que la matriz transpuesta  y $ (A.B)^t $. Tiene dimensiones 2x3. 2 Filas y 3 columnas.

### Lugares de una matriz

En el ejercicio 3 de la práctica 1 practicaron cómo acceder a los distintos elementos de una matriz.

**IMPORTANTE: los índices en Python empiezan en 0**

Por ejemplo, para acceder al coeficiente $a_{i,j}$ de una matriz $A$ escribimos $A[i-1,j-1]$. 

Para acceder a una fila de $A$ usamos los dos puntos ":" que indican "todo". Por ejemplo, si queremos la fila $i$ de $A$ escribimos $A[i-1,:]$.

## Ejercicio

Calcular los siguientes elementos:
$a_{2,3}$, la fila 3 de $A$, la columna 1 de $A.B$, $(B^t)_{1,3}$

In [41]:
#Fila 2 Columna 3 de la matriz A
A23= A[1,2] #o A[2-1,3-1]

#Fila 3 de la Matriz A
f3A= A[2,:] #o A[3-1,:]


#Columna 1 de la Matriz A.B
AB = A@B
c1AB = AB[:,0]

#Elemento de la fila 1 y columna 3
Bt = B.T
Bt13 = Bt[1-1,3-1]


###
print('Matriz A\n',A)
print('Elemento de la matriz A: Fila 2 columna 3:',A23)
print('')
print('Fila 3 de la matriz A:',f3A)
print('')
print('Matriz A.B\n',AB)
print('Columna 1 de la matriz A.B:',c1AB)
print('')
print('Matriz B transpuesta:\n',Bt)
print('Elemento fila 1 columna 3 de Bt',Bt13)



Matriz A
 [[ 0  1  2]
 [-3 -4 -5]
 [ 6  7  8]]
Elemento de la matriz A: Fila 2 columna 3: -5

Fila 3 de la matriz A: [6 7 8]

Matriz A.B
 [[  4   5]
 [-13 -11]
 [ 22  17]]
Columna 1 de la matriz A.B: [  4 -13  22]

Matriz B transpuesta:
 [[ 1  0  2]
 [ 0 -1  3]]
Elemento fila 1 columna 3 de Bt 2


### Inversa y determinante

El determinante es una función que se aplica a matrices **cuadradas** y devuelve por resultado un escalar.
$$A\in\mathbb{K}^{n\times n}, \quad det(A)\in\mathbb{K}$$
Esta función determina si una matriz cuadrada es inversible o no. Recordar que $A \in \mathbb{K}^{n\times n}$ es inversible $\iff \quad det(A)\neq 0$

Ambas funciones están en Numpy dentro del paquete "linalg". Por ejemplo:

In [42]:
d=np.linalg.det(A) #¿Es A inversible?
d 

0.0

El determinante de la Matriz A es nulo, por lo que no es inversible, hay una combinación lineal. Cuando la matriz no es inversible se dice que es SINGULAR.

In [46]:
try:
    Ainv=np.linalg.inv(A) 
except:
    print('No es posible realizar el calculo. La matriz es Singular')

No es posible realizar el calculo. La matriz es Singular


In [57]:
try:
    Binv=np.linalg.det(B) #si la matriz no es cuadrada salta un error
except np.linalg.LinAlgError as error:
    if "Last 2 dimensions of the array must be square" in str(error):
        print("Last 2 dimensions of the array must be square")

Last 2 dimensions of the array must be square


### Funciones útiles y ciclos for:

Nos será útil en esta materia la función "range" para indicar rangos de valores para nuestras variables.
Por ejemplo

In [59]:
for i in range(10): 
    print(i)
print("Terminé") #Prestar atención a la indentación

0
1
2
3
4
5
6
7
8
9
Terminé


In [60]:
for i in range(1,5):
    print(i)

1
2
3
4


In [61]:
# Va de 2 en 2
for i in range(3,15,2):
    print(i)

3
5
7
9
11
13


Calculemos ahora su suma. Por ejemplo, para sumar los números naturales del 1 al 10 inclusive.
$$
\sum_{i=0}^{10} i
$$
Hacemos:

In [62]:
suma = 0
for i in range(0, 11):
    suma = suma + i
print("Suma: ", suma)

Suma:  55


## Ejercicio: 
Sumar los cuadrados de los números naturalesdel 5 al 1000 inclusive.
$$
\sum_{i=5}^{1000} i^2
$$
**Resultado**=333833470

In [66]:
suma = 0
for i in range(5,1001):
    suma = suma + i**2
print('El resultado es: ',suma)

El resultado es:  333833470


### Sumar lugares de una matriz
Los elementos de la fila $i$ de una matriz $A \in \mathbb{K}^{m\times n}$ son $F_i=(a_{i1} \, a_{i2} \, \ldots \, a_{in})$, cuya suma $a_{i1}+a_{i2}+ \ldots + a_{in}$ se puede escribir usando una sumatoria:
$$S_i=\sum_{j=1}^{n}a_{ij}$$
Si queremos sumar **todos** los elementos de una matriz podemos sumar los resultados de las $m$ filas $S_1+S_2+ \ldots + S_m = \sum_{i=1}^{m} S_i$, quedando una doble sumatoria:
$$S=\sum_{i=1}^{m} \sum_{j=1}^{n}a_{ij}$$

## Ejercicio

Usar un ciclo for para calcular:

**a)** La suma de los elementos de la segunda fila de $A$. 

_La función **np.sum()** realiza la suma, la podemos usar para verificar nuestro resultado._

**b)** La traza de la matriz $A$, que es la suma de los elementos de la diagonal principal $tr(A)=\sum_{i=1}^n a_{ii}$.

_La función **np.trace()** realiza la suma, la podemos usar para verificar nuestro resultado._

**c)** La suma de todos los elementos de la matriz $B$ (vamos a necesitar dos ciclos, uno por cada sumatoria).

_La función **np.sum()** realiza la suma, la podemos usar para verificar nuestro resultado._


In [86]:
#Ciclo for que calcula la suma de todos los elementos de la segunda fila de A
suma = 0
columnas = A.shape[1]
for col in range(columnas):
    suma = A[2-1,col] + suma

print('La suma de todos los elementos de la segunda fila de A es:',suma)
print('Verificando con funcion np.sum: ',np.sum(A[2-1,:]))
    

La suma de todos los elementos de la segunda fila de A es: -12
Verificando con funcion np.sum:  -12


In [92]:
#Ciclo que calcula la traza de la matriz A.
#Suma todos los valores de la diagonal

suma = 0
for i in range(A.shape[1]):
    suma = A[i,i] + suma 

print('El valor de la traza calculada con for es:',suma)
print('El valor de la traza calculada con np.trace',np.trace(A))


El valor de la traza calculada con for es: 4
El valor de la traza calculada con np.trace 4


In [97]:
#Ciclo que calcula la cantidad de elementos de una matriz B
suma = 0
for fila in range(3):
    for col in range(2):
        suma = B[fila,col] + suma

print('La suma  de elementos de la matriz B es:',suma)
print('Calculada con np.sum() es:',np.sum(B))

La suma  de elementos de la matriz B es: 5
Calculada con np.sum() es: 5


### Obs: 
La función **"len()"** de python puede ser útil por ejemplo para el ítem b). La función calcula la cantidad de elementos de una objeto. Por ejemplo, 

In [93]:
l=len([1,0,-3,2])
l

4

Como las matrices las ingresamos como un conjunto de filas, la función len me devolverá la cantidad de filas de la matriz. Por ejemplo,

In [104]:
for i in range(len(A)):
    print (A[i,i])  #¿Qué pasa si se lo aplicamos a la matriz B?

0
-4
8


Y como última observación, puede ser útil también en este caso, la función **"np.diag()"** que devuelve un vector con la diagonal principal de la matriz.

In [ ]:
dA=np.diag(A)
dB=np.diag(B)
print(dA)
print(dB)

Veamos algunos ejemplos con **if**:

In [98]:
a = 15
b = 5
if(a>b):
    print(a, " es mayor que ", b)

15  es mayor que  5


In [99]:
# if - else
a = 15
b = 5
if(a>b):
    print(a, " es mayor que ", b)
else:
    print(a, " no es mayor que ", b)

15  es mayor que  5


In [ ]:
# if - elif - else
a = 5
b = 5
if(a>b):
    print(a, " es mayor que ", b)
elif (b>a):
    print(b, " es mayor que ", a)
else:
    print(a, " es igual a ", b)

## Ejercicios

**a)** Calcular la suma de los elementos arriba de la diagonal de $A$, o sea, calcular $$\sum_{i=1}^{m}\sum_{j>i}a_{ij}$$
**b)** Calcular el producto de los elementos no nulos de la matriz $A$.

### Item A


In [132]:
#Ciclo que calcula la suma de los elementos por encima de la diagonal

suma = 0
for fila in range(A.shape[0]):
    for col in range(A.shape[1]):
        #Si el indice de la columna es mayor que el indice de fila realiza la suma
        if col > fila:
            suma = A[fila,col] + suma

print('La suma de los valores por encima de la diagonal usando for es:', suma)
print('La suma de los valores usando np.sum(np.triu(A,1)) es:',np.sum(np.triu(A,1)))


La suma de los valores por encima de la diagonal usando for es: -2
La suma de los valores usando np.sum(np.triu(A,1)) es: -2


### Item B

In [135]:
#Ciclo for que calcula el producto de los elementos no nulos de la matriz
producto = 1
for fila in range(A.shape[0]):
    for col in range(A.shape[1]):
        if A[fila,col] != 0:
            producto = A[fila,col] * producto
print('El producto de los elementos no nulos usando for de la matriz A es: ',producto)


El producto de los elementos no nulos usando for de la matriz A es:  -40320


In [161]:
#Usando funciones

#Obtengo los indices de los elementos no nulos
#Devuelve dos arrays con los indices de filas y columnas 
elem_no_nulos = np.nonzero(A) 

#Realizo la multiplicacion de los elementos no nulos y devuelvo por pantalla
print(np.prod(A[elem_no_nulos]))

-40320


## Otra forma de indexar y seleccionar valores de una matriz

In [157]:
A[np.array([1,2]),np.array([2,2])]

array([-5,  8])

### Definir funciones

Por último, definamos algunas funciones. **¡¡En los "videos preliminares" en el campus tienen más detalles!!**

Por ejemplo:

In [ ]:
def suma(a,b):
    c = a + b
    return(c)

In [ ]:
suma(3,12)

Otro ejemplo:

In [ ]:
def comparar(a, b):
    if(a>b):
        print(a, " es mayor que ", b)
    elif (b>a):
        print(b, " es mayor que ", a)
    else:
        print(a, " es igual a ", b)

In [ ]:
comparar(3,12)

## Ejercicios

**a)** Realizar el Ejercicio 14 de la Práctica 1.

**b)** Escribir un programa que reciba un vector $v$ en $R^n$ y devuelva cuántas coordenadas de $v$ son mayores que 5.

_Obs: Recordar que puede ser útil la función "len" a la hora de usar "range" para recorrer todas las componentes de una lista.

In [ ]:
#completar